name = "savaspinbonus-net"
compatibility_date = "2025-01-01"
pages_build_output_dir = "."

[vars]
REF_URL = "https://serffigxjssvpeo.help/RC2TZM?sub_id_3=savaspinbonus.net"
HMAC_KEY = "e2d59ade4b437386c9e30ea1969e34a0c442c7ba1dc6e4d7319ce21db789f95a"
COOKIE_NAME = "bti"
PLAY_PATH = "go"
BUTTON_ID = "p0002632ed91c06b9ce84d05bf6e2d4b0"
GATE_SALT = "69788c82770d125a"
GO_URLS = "[\"https://monitorre.top/go/ref\", \"https://firespot.click/go/ref\", \"https://fintechfox.click/go/ref\", \"https://buffout.click/go/ref\"]"
GO_TOKEN = "6c27a2676e6fb97970145a1c9daa1d717ea137c80518a24c"
GO_COOKIE = "4e5d"
CTA_SELECTOR = ".play-button"
